version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5442:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser_test
      POSTGRES_PASSWORD: mypassword_test
      POSTGRES_DB: mydb_test
    ports:
      - '5452:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data_test

volumes:
  postgres-data:
